### ISSUE TITLE
Value applied is unmodified roll rather than modified total.

### ISSUE THREAD

**Issue by ian-aus** [wintersleepAI/chatdamageswnr#1]
Hi winter, great module thanks.

I've noticed that only the value of the raw dice roll is applied and not the modified value / total result.

E.G. on a 1d6+1 where a 5 is rolled, the damage applied is 5 where it should be a 6.

I am a novice dev so take the following with grain of salt

On line 22 of chatdamageswnr.js you use message.roll.dice[1].total which when inspecting a chatmessage object using console, appears to me to contains the unmodified dice roll.

I think the modified result is contained in message.roll.terms[0].rolls[1].total.

Cheers
Ian

**Comment by ian-aus** [comment]
I tested using message.roll.terms[0].rolls[1].total and it works for me.

**Comment by wintersleepAI** [comment]
thanks! i will take a look at it this in the next couple of days!

**Comment by wintersleepAI** [comment]
sorry slammed with trying to get out the next system release. will try to test this out on my end and push a fix soon!

**Comment by ian-aus** [comment]
No worries. I have a bandaid fix in my game using a hook macro copy of your script with the fix applied - take your time!

**Comment by wintersleepAI** [comment]
ok poking around some. i see the issue thanks. 

it looks like the following also works. going to poke around with this and see what is right.
                total = message.roll.terms[0].results[1].result;

looks like this is really wrong when shock damage is added (not sure if you are playing off of my fork or spice kings original).

**Comment by ian-aus** [comment]
Running the original for now but I may swap. I don't think the original puts shock damage in the attack, we've been adding it manually. I didn't test shock, sorry, that was an oversight on my part.

**Comment by wintersleepAI** [comment]
no its only in my fork (https://github.com/wintersleepAI/foundry-swnr) that shows it currently. 
![image](https://user-images.githubusercontent.com/88955427/136891337-a6120292-ff78-47e8-a740-4fe34642c6da.png)
  working through how to add the right total to the right 2 rolls. hope to get fixed tomorrow.

**Comment by wintersleepAI** [comment]
i totally dropped the ball on this and finally fixed.

i am not sure if the upgrade button in foundry is working though (looks like I might have botched something in the original release set up). would you be willing to test?

**Comment by ian-aus** [comment]
Hey Winter. I upgraded to 0.2 without issue and tested. It is working perfectly. Thanks again!

**Comment by wintersleepAI** [comment]
thanks much for finding, identifying where the problem was, and testing! sorry it took so long to fix!
