### ISSUE TITLE
Error in Console

### ISSUE THREAD

**Issue by Cup-of-Coffee** [wintersleepAI/chatdamageswnr#2]
Foundry gives a error on startup of a game, but otherwise the module appears to be working properly.

![Screenshot 2022-09-28 183329](https://user-images.githubusercontent.com/39238717/193052650-2367585b-3ed9-4f07-8e6b-d97ae65f84c5.png)

I'm running Foundry version 10 - build 286.

**Comment by Cup-of-Coffee** [comment]
Additionally, when starting up Foundry, this warning is given.

![Screenshot 2022-09-29 125421](https://user-images.githubusercontent.com/39238717/193092198-a1208590-e9a4-4ad0-b0ae-9cf27e229a5a.png)

**Comment by wintersleepAI** [comment]
module is no longer developed as functionality is in core system
